#!/bin/bash

#good plan for you guys for a few years

echo "Hello Igor and Krystyna"
sleep 2
echo "Igor!"
sleep 2
echo "you propose to Krystyna"
sleep 2
echo "Krystyna, you say: are you serious?"
sleep 2
echo "Igor, you say: yes,I am totally serious"
sleep 2
echo "will you marry me Krystyna!?"
sleep 2
echo "Krystyna: it is hard to breathe for me, yes Igor, I am marry you"
sleep 2
echo "Krystyna you say: did you just ask me to marry you for reall?"
sleep 2
echo "Krystyna you say: yes I agree to be your wife, but is it happening with me now?"
sleep 2
echo "Igor you say: yes Krystyna, I just asked if you marry me, and you said yes, and now we are practically husband and wife, we just need to plan when to have a wedding ceremony and plann a honey moon to some cool place for a week or 10 days, where we going to make some kids quickly, because we need to live  now"
sleep 7
echo "Krystyna you say: oh my Gosh my head is spinning,Igor are you going to understand all my moods all my naughty things I do and do you like me the way I am ? my body , my character, my attitude?"
sleep 5
echo "Igor you say: yes, Krystyna, I like you the way you are and you are perfect for me as you look as you behave and your attitude, I like it and I am your husband till the day I die, I almost love you"
